[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
staking_class = "E4hk9WgWo7dxFHfnE9U7nfMskUsMdkQr3LFZ6KX2ciFm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
