[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
xero = "E7s9u89mMuVGULoSnY6PA1yLkcAev8MeTMxxA33pskFo"

[programs.devnet]
xero = "E7s9u89mMuVGULoSnY6PA1yLkcAev8MeTMxxA33pskFo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/sebatustra/my-solana-wallet/my-keypair.json"

# [provider]
# cluster = "Localnet"
# wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
